name: Create File
on:
  workflow_dispatch:
  schedule:
     - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4
          python -m pip install pandas
          
      - name: Run
        run:
          python trophy.py
#           git config --global user.email ${{ secrets.EMAIL }}
#           git config --global user.name ${{ secrets.NAME }}
#           git add ./data
#           git commit -m "commit"
#           git push origin main
      - name: Upload artifact
        run: |
          echo "Uploading artifact"
          echo "::set-output name=artifact_path::$(pwd)/darksouls3.csv"
        env:
          ARTIFACT_NAME: darksouls3.csv
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ steps.upload-artifact.outputs.artifact_path }}
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.TOKEN }}
#           publish_dir: ./data
