name: Create File
on:
  workflow_dispatch:
  schedule:
     - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4
          python -m pip install pandas
          
      - name: Run
        run:
          python trophy.py
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git add .
          git commit -m "commit"
          git push

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.TOKEN }}
#           publish_dir: ./data
