name: Create File
on:
  workflow_dispatch:
  schedule:
     - cron: '0 22 * * *'

jobs:
  - name: 単行
    run: echo "line" > test.txt
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: create file
      run: |
        bash create_file.sh
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
